# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0002_auto_20180506_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(null=True, upload_to='images/%Y-%m-%d'),
        ),
    ]
